Add support to FuSeBMC
sosy-lab/benchexec pull request #627
Opened 2020-10-15 18:59 UTC by rafaelsamenezes

This intends to add the support for FuSeBMC https://github.com/kaled-alshmrany/FuSeBMC

2020-10-16 05:39 UTC, PhilippWendler requested changes

2020-10-16 05:39 UTC, PhilippWendler commented on benchexec/tools/FuSeBMC.py
> +class Tool(benchexec.tools.template.BaseTool):
For a new tool-info module, would you mind writing it for our new, more convenient, API based on `BaseTool2`? We have a [migration guide](https://github.com/sosy-lab/benchexec/blob/master/doc/tool-integration.md#migrating-tool-info-modules-to-new-api).

2020-10-16 05:39 UTC, PhilippWendler commented on benchexec/tools/FuSeBMC.py
> +    This class serves as tool adaptor for ESBMC (http://www.esbmc.org/)
There is already a tool-info module for ESBMC, is this comment wrong?

2020-10-16 05:39 UTC, PhilippWendler commented on benchexec/tools/FuSeBMC.py
> +    REQUIRED_PATHS = ["esbmc", "esbmc-wrapper.py", "my_instrument"]
Having the executable that is returned from `executable()` in this is redundant.

2020-10-16 05:39 UTC, PhilippWendler commented on benchexec/tools/FuSeBMC.py
> +    def allInText(self, words, text):
This helper method seems unnecessary because it is always only called with a single-element list. `if word in text` is enough instead.

2020-10-16 05:39 UTC, PhilippWendler commented on benchexec/tools/FuSeBMC.py
> +        assert len(tasks) == 1, "only one inputfile supported"
After changing to `BaseTool2`, this assert is no longer necessary because you can simply use `task.single_input_file`.

2020-10-16 20:15 UTC, rafaelsamenezes commented
@PhilippWendler when porting it I looked over some examples and saw that cpa-witness2test.py only inherits from cpachecker. FuSeBMC wrapper in a nutshell is the same as esbmc with the only real change being the REQUIRED_PATHS. May I just do that instead of porting it?

2020-10-17 11:18 UTC, PhilippWendler commented
Sure. This is recommended if you expect that any changes to ESBMC's tool-info module (e.g., improving output parsing or adding required files) will also be relevant for your tool.

2020-10-20 16:20 UTC, PhilippWendler reviewed
Looks good, please just fix format as requested by CI.

2020-10-21 06:00 UTC, PhilippWendler approved these changes

2020-10-21 06:00 UTC, merged

2020-10-21 07:16 UTC, PhilippWendler commented
Unfortunately, just after I merged the PR, I noticed the name of the file, which is `FuSeBMC` and does not match our typical name of "lowercase tool-name". Is it ok for you if I rename it?